import mongoose from 'mongoose'
import dotenv from 'dotenv'
import Place from '../models/Place.js'

dotenv.config()

const seedPlaces = [
  // ───── EXISTING 12 PLACES ─────
  {
    name: 'Eiffel Tower',
    description: 'Iconic iron lattice monument in Paris, offering breathtaking panoramic views of the city from its observation decks. A must-visit symbol of France.',
    category: 'Tourist',
    latitude: 48.8584,
    longitude: 2.2945,
    address: '5 Avenue Anatole France, 75007 Paris',
    city: 'Paris',
    country: 'France',
    priceRange: 'Moderate',
    rating: 4.7,
    reviews: 12500,
    openingHours: '9:00 AM - 12:45 AM',
    image: 'https://images.unsplash.com/photo-1543349689-9a4d426bee8e?w=400&h=300&fit=crop'
  },
  {
    name: 'Statue of Liberty',
    description: 'Colossal neoclassical sculpture on Liberty Island, a universal symbol of freedom and democracy gifted by France to the United States.',
    category: 'Tourist',
    latitude: 40.6892,
    longitude: -74.0445,
    address: 'Liberty Island, New York, NY 10004',
    city: 'New York',
    country: 'USA',
    priceRange: 'Budget',
    rating: 4.6,
    reviews: 8900,
    openingHours: '9:30 AM - 5:00 PM',
    image: 'https://images.unsplash.com/photo-1503174971373-b1f69850bded?w=400&h=300&fit=crop'
  },
  {
    name: 'Great Wall of China',
    description: 'Ancient fortification spanning thousands of miles across northern China, one of the most impressive architectural feats in history.',
    category: 'Historical',
    latitude: 40.4319,
    longitude: 116.5704,
    address: 'Huairou District, Beijing',
    city: 'Beijing',
    country: 'China',
    priceRange: 'Budget',
    rating: 4.8,
    reviews: 15600,
    openingHours: '8:00 AM - 5:00 PM',
    image: 'https://images.unsplash.com/photo-1508804185872-d7badad00f7d?w=400&h=300&fit=crop'
  },
  {
    name: 'Swiss Alps',
    description: 'Stunning mountain range with world-class hiking trails, ski resorts, and breathtaking views of snow-capped peaks and pristine valleys.',
    category: 'Nature',
    latitude: 46.5775,
    longitude: 8.3932,
    address: 'Valais, Switzerland',
    city: 'Valais',
    country: 'Switzerland',
    priceRange: 'Moderate',
    rating: 4.9,
    reviews: 7200,
    openingHours: '24/7',
    image: 'https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=400&h=300&fit=crop'
  },
  {
    name: 'Tokyo Fish Market',
    description: 'Bustling market with the freshest seafood and authentic Japanese street food. Experience the vibrant energy of Tokyo\'s culinary culture.',
    category: 'Food',
    latitude: 35.6655,
    longitude: 139.7722,
    address: '4 Chome Tsukiji, Chuo Ward, Tokyo',
    city: 'Tokyo',
    country: 'Japan',
    priceRange: 'Budget',
    rating: 4.5,
    reviews: 5600,
    openingHours: '5:00 AM - 2:00 PM',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop'
  },
  {
    name: 'Marina Bay Sands',
    description: 'Luxury integrated resort with world-class shopping, dining, and entertainment. Features the iconic infinity pool with panoramic city views.',
    category: 'Shopping',
    latitude: 1.2855,
    longitude: 103.8565,
    address: '10 Bayfront Avenue, Singapore',
    city: 'Singapore',
    country: 'Singapore',
    priceRange: 'Premium',
    rating: 4.6,
    reviews: 9100,
    openingHours: '10:00 AM - 10:00 PM',
    image: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=400&h=300&fit=crop'
  },
  {
    name: 'Machu Picchu',
    description: 'Ancient Incan citadel set high in the Andes Mountains, a UNESCO World Heritage site and one of the New Seven Wonders of the World.',
    category: 'Historical',
    latitude: -13.1631,
    longitude: -72.5450,
    address: 'Cusco Region, Peru',
    city: 'Cusco',
    country: 'Peru',
    priceRange: 'Premium',
    rating: 4.9,
    reviews: 11800,
    openingHours: '6:00 AM - 5:30 PM',
    image: 'https://images.unsplash.com/photo-1526392060635-9d6019884377?w=400&h=300&fit=crop'
  },
  {
    name: 'Whistler Ski Resort',
    description: 'World-class ski resort in British Columbia with over 200 marked runs, stunning alpine scenery, and vibrant après-ski culture.',
    category: 'Activities',
    latitude: 50.1163,
    longitude: -122.9574,
    address: '4545 Blackcomb Way, Whistler, BC',
    city: 'Whistler',
    country: 'Canada',
    priceRange: 'Premium',
    rating: 4.7,
    reviews: 6700,
    openingHours: '8:30 AM - 4:00 PM',
    image: 'https://images.unsplash.com/photo-1551524559-8af4e6624178?w=400&h=300&fit=crop'
  },
  {
    name: 'Santorini Sunset',
    description: 'Experience the magical blue-domed churches and white-washed buildings against stunning Mediterranean sunsets on this Greek island.',
    category: 'Nature',
    latitude: 36.3932,
    longitude: 25.4615,
    address: 'Oia, Santorini',
    city: 'Santorini',
    country: 'Greece',
    priceRange: 'Moderate',
    rating: 4.9,
    reviews: 9800,
    openingHours: '24/7',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac1fe?w=400&h=300&fit=crop'
  },
  {
    name: 'Grand Bazaar Istanbul',
    description: 'One of the world\'s oldest and largest covered markets, filled with exotic spices, handcrafted textiles, and unique treasures.',
    category: 'Shopping',
    latitude: 41.0082,
    longitude: 28.9784,
    address: 'Beyazit, 34126 Fatih, Istanbul',
    city: 'Istanbul',
    country: 'Turkey',
    priceRange: 'Budget',
    rating: 4.5,
    reviews: 7400,
    openingHours: '8:30 AM - 7:00 PM',
    image: 'https://images.unsplash.com/photo-1527838832700-5059252407fa?w=400&h=300&fit=crop'
  },
  {
    name: 'Bali Rice Terraces',
    description: 'Stunning emerald green rice terraces cascading down volcanic hillsides, showcasing traditional Balinese irrigation and agriculture.',
    category: 'Nature',
    latitude: -8.5069,
    longitude: 115.2625,
    address: 'Tegallalang, Gianyar, Bali',
    city: 'Ubud',
    country: 'Indonesia',
    priceRange: 'Free',
    rating: 4.6,
    reviews: 5200,
    openingHours: '7:00 AM - 6:00 PM',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=400&h=300&fit=crop'
  },
  {
    name: 'Kyoto Food Tour',
    description: 'Explore the authentic flavors of Kyoto with traditional Japanese cuisine including matcha, ramen, and kaiseki dining experiences.',
    category: 'Food',
    latitude: 35.0116,
    longitude: 135.7681,
    address: 'Nishiki Market, Kyoto',
    city: 'Kyoto',
    country: 'Japan',
    priceRange: 'Moderate',
    rating: 4.8,
    reviews: 4300,
    openingHours: '9:00 AM - 6:00 PM',
    image: 'https://images.unsplash.com/photo-1553621042-f6e147245754?w=400&h=300&fit=crop'
  },

  // ───── NEW FAMOUS TRAVEL PLACES ─────
  {
    name: 'Taj Mahal',
    description: 'A stunning white marble mausoleum in Agra, built by Mughal Emperor Shah Jahan in memory of his wife. One of the New Seven Wonders of the World.',
    category: 'Historical',
    latitude: 27.1751,
    longitude: 78.0421,
    address: 'Dharmapuri, Forest Colony, Tajganj, Agra',
    city: 'Agra',
    country: 'India',
    priceRange: 'Budget',
    rating: 4.8,
    reviews: 18200,
    openingHours: '6:00 AM - 6:30 PM',
    image: 'https://images.unsplash.com/photo-1564507592333-c60657eea523?w=400&h=300&fit=crop'
  },
  {
    name: 'Colosseum',
    description: 'Ancient Roman amphitheatre in the heart of Rome, the largest ever built. This iconic arena once hosted gladiator battles and public spectacles.',
    category: 'Historical',
    latitude: 41.8902,
    longitude: 12.4922,
    address: 'Piazza del Colosseo, 1, 00184 Roma',
    city: 'Rome',
    country: 'Italy',
    priceRange: 'Moderate',
    rating: 4.7,
    reviews: 14500,
    openingHours: '8:30 AM - 7:00 PM',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=400&h=300&fit=crop'
  },
  {
    name: 'Christ the Redeemer',
    description: 'Towering Art Deco statue of Jesus Christ atop Corcovado Mountain in Rio de Janeiro, offering stunning panoramic views of the city and coastline.',
    category: 'Tourist',
    latitude: -22.9519,
    longitude: -43.2105,
    address: 'Parque Nacional da Tijuca, Rio de Janeiro',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    priceRange: 'Moderate',
    rating: 4.8,
    reviews: 13100,
    openingHours: '8:00 AM - 7:00 PM',
    image: 'https://images.unsplash.com/photo-1483729558449-99ef09a8c325?w=400&h=300&fit=crop'
  },
  {
    name: 'Petra',
    description: 'Ancient city carved into rose-red cliffs in southern Jordan, famous for its rock-cut architecture and the iconic Treasury facade.',
    category: 'Historical',
    latitude: 30.3285,
    longitude: 35.4444,
    address: 'Wadi Musa, Jordan',
    city: 'Wadi Musa',
    country: 'Jordan',
    priceRange: 'Moderate',
    rating: 4.9,
    reviews: 10400,
    openingHours: '6:00 AM - 6:00 PM',
    image: 'https://images.unsplash.com/photo-1579606032821-4e6161c81571?w=400&h=300&fit=crop'
  },
  {
    name: 'Angkor Wat',
    description: 'Largest religious temple complex in the world, a breathtaking example of Khmer architecture surrounded by lush jungle in Cambodia.',
    category: 'Historical',
    latitude: 13.4125,
    longitude: 103.8670,
    address: 'Krong Siem Reap, Cambodia',
    city: 'Siem Reap',
    country: 'Cambodia',
    priceRange: 'Budget',
    rating: 4.8,
    reviews: 11200,
    openingHours: '5:00 AM - 5:30 PM',
    image: 'https://images.unsplash.com/photo-1539650116574-8efeb43e2750?w=400&h=300&fit=crop'
  },
  {
    name: 'Niagara Falls',
    description: 'Spectacular group of three waterfalls straddling the US-Canada border, known for their incredible power and mesmerizing beauty.',
    category: 'Nature',
    latitude: 43.0962,
    longitude: -79.0377,
    address: 'Niagara Falls, Ontario, Canada',
    city: 'Niagara Falls',
    country: 'Canada',
    priceRange: 'Free',
    rating: 4.7,
    reviews: 16800,
    openingHours: '24/7',
    image: 'https://images.unsplash.com/photo-1489447068241-b3490214e879?w=400&h=300&fit=crop'
  },
  {
    name: 'Sydney Opera House',
    description: 'Masterpiece of 20th-century architecture on Sydney Harbour, hosting over 1,500 performances each year in its iconic sail-shaped halls.',
    category: 'Tourist',
    latitude: -33.8568,
    longitude: 151.2153,
    address: 'Bennelong Point, Sydney NSW 2000',
    city: 'Sydney',
    country: 'Australia',
    priceRange: 'Moderate',
    rating: 4.7,
    reviews: 10900,
    openingHours: '9:00 AM - 8:30 PM',
    image: 'https://images.unsplash.com/photo-1624138784614-87fd1b6528f8?w=400&h=300&fit=crop'
  },
  {
    name: 'Grand Canyon',
    description: 'Awe-inspiring, mile-deep natural wonder carved by the Colorado River over millions of years, with stunning layered rock formations.',
    category: 'Nature',
    latitude: 36.1069,
    longitude: -112.1129,
    address: 'Grand Canyon Village, AZ 86023',
    city: 'Grand Canyon Village',
    country: 'USA',
    priceRange: 'Budget',
    rating: 4.9,
    reviews: 14200,
    openingHours: '24/7',
    image: 'https://images.unsplash.com/photo-1474044159687-1ee9f3a51722?w=400&h=300&fit=crop'
  },
  {
    name: 'Maldives Beaches',
    description: 'Paradise islands with crystal-clear turquoise waters, powdery white sand beaches, and vibrant coral reefs perfect for snorkeling.',
    category: 'Nature',
    latitude: 3.2028,
    longitude: 73.2207,
    address: 'Male Atoll, Maldives',
    city: 'Male',
    country: 'Maldives',
    priceRange: 'Premium',
    rating: 4.9,
    reviews: 8700,
    openingHours: '24/7',
    image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=400&h=300&fit=crop'
  },
  {
    name: 'Pyramids of Giza',
    description: 'Ancient Egyptian pyramids and the Great Sphinx, the last surviving Wonder of the Ancient World standing for over 4,500 years.',
    category: 'Historical',
    latitude: 29.9792,
    longitude: 31.1342,
    address: 'Al Haram, Giza Governorate, Egypt',
    city: 'Giza',
    country: 'Egypt',
    priceRange: 'Budget',
    rating: 4.7,
    reviews: 13700,
    openingHours: '7:00 AM - 5:00 PM',
    image: 'https://images.unsplash.com/photo-1503177119275-0aa32b3a9368?w=400&h=300&fit=crop'
  },
  {
    name: 'Dubai Mall & Burj Khalifa',
    description: 'The world\'s tallest building alongside the largest shopping mall, featuring the spectacular Dubai Fountain show and observation deck.',
    category: 'Shopping',
    latitude: 25.1972,
    longitude: 55.2744,
    address: 'Financial Centre Road, Downtown Dubai',
    city: 'Dubai',
    country: 'UAE',
    priceRange: 'Premium',
    rating: 4.8,
    reviews: 17600,
    openingHours: '10:00 AM - 12:00 AM',
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=400&h=300&fit=crop'
  },
  {
    name: 'Northern Lights, Iceland',
    description: 'Witness the magical Aurora Borealis dance across the Icelandic sky with vibrant greens, purples, and pinks. Best viewed Sep–Mar.',
    category: 'Nature',
    latitude: 64.1466,
    longitude: -21.9426,
    address: 'Reykjavik, Iceland',
    city: 'Reykjavik',
    country: 'Iceland',
    priceRange: 'Moderate',
    rating: 4.9,
    reviews: 6500,
    openingHours: '24/7 (Sep - Mar)',
    image: 'https://images.unsplash.com/photo-1483347756197-71ef80e95f73?w=400&h=300&fit=crop'
  },
  {
    name: 'Champs-Elysees & Arc de Triomphe',
    description: 'The most famous avenue in the world, lined with luxury shops, cafes, and theaters, leading up to the iconic Arc de Triomphe monument.',
    category: 'Shopping',
    latitude: 48.8738,
    longitude: 2.2950,
    address: 'Place Charles de Gaulle, 75008 Paris',
    city: 'Paris',
    country: 'France',
    priceRange: 'Premium',
    rating: 4.6,
    reviews: 11300,
    openingHours: '10:00 AM - 11:00 PM',
    image: 'https://images.unsplash.com/photo-1509439581779-6298f75bf6e5?w=400&h=300&fit=crop'
  },
  {
    name: 'Ha Long Bay',
    description: 'UNESCO World Heritage site with thousands of limestone karsts and islands rising from emerald waters, best explored by traditional junk boat.',
    category: 'Nature',
    latitude: 20.9101,
    longitude: 107.1839,
    address: 'Quang Ninh Province, Vietnam',
    city: 'Ha Long',
    country: 'Vietnam',
    priceRange: 'Budget',
    rating: 4.7,
    reviews: 8900,
    openingHours: '24/7',
    image: 'https://images.unsplash.com/photo-1528127269322-539801943592?w=400&h=300&fit=crop'
  },
  {
    name: 'Table Mountain',
    description: 'Flat-topped mountain overlooking Cape Town, offering spectacular panoramic views, unique fynbos vegetation, and world-class hiking trails.',
    category: 'Nature',
    latitude: -33.9628,
    longitude: 18.4098,
    address: 'Table Mountain National Park, Cape Town',
    city: 'Cape Town',
    country: 'South Africa',
    priceRange: 'Moderate',
    rating: 4.8,
    reviews: 7600,
    openingHours: '8:00 AM - 6:00 PM',
    image: 'https://images.unsplash.com/photo-1580060839134-75a5edca2e99?w=400&h=300&fit=crop'
  },
  {
    name: 'Bangkok Street Food',
    description: 'Explore the vibrant street food culture of Bangkok with pad thai, mango sticky rice, tom yum soup and more at Chinatown and Khao San Road.',
    category: 'Food',
    latitude: 13.7563,
    longitude: 100.5018,
    address: 'Yaowarat Road, Chinatown, Bangkok',
    city: 'Bangkok',
    country: 'Thailand',
    priceRange: 'Budget',
    rating: 4.7,
    reviews: 9400,
    openingHours: '5:00 PM - 12:00 AM',
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400&h=300&fit=crop'
  },
  {
    name: 'Serengeti National Park',
    description: 'Iconic African safari destination known for the Great Migration, diverse wildlife including the Big Five, and vast golden savanna plains.',
    category: 'Nature',
    latitude: -2.3333,
    longitude: 34.8333,
    address: 'Serengeti, Mara Region, Tanzania',
    city: 'Serengeti',
    country: 'Tanzania',
    priceRange: 'Premium',
    rating: 4.9,
    reviews: 5800,
    openingHours: '6:00 AM - 6:00 PM',
    image: 'https://images.unsplash.com/photo-1516426122078-c23e76319801?w=400&h=300&fit=crop'
  },
  {
    name: 'Venice Canals',
    description: 'Romantic city built on water with stunning gondola rides through winding canals, historic palaces, and the magnificent St. Mark\'s Square.',
    category: 'Tourist',
    latitude: 45.4408,
    longitude: 12.3155,
    address: 'Venice, Metropolitan City of Venice, Italy',
    city: 'Venice',
    country: 'Italy',
    priceRange: 'Moderate',
    rating: 4.7,
    reviews: 12100,
    openingHours: '24/7',
    image: 'https://images.unsplash.com/photo-1514890547357-a9ee288728e0?w=400&h=300&fit=crop'
  },
  {
    name: 'Great Barrier Reef',
    description: 'World\'s largest coral reef system off the coast of Australia, offering incredible snorkeling and diving among 1,500 species of fish.',
    category: 'Activities',
    latitude: -18.2871,
    longitude: 147.6992,
    address: 'Queensland, Australia',
    city: 'Cairns',
    country: 'Australia',
    priceRange: 'Premium',
    rating: 4.9,
    reviews: 8300,
    openingHours: '7:00 AM - 5:00 PM',
    image: 'https://images.unsplash.com/photo-1582967788606-a171c1080cb0?w=400&h=300&fit=crop'
  },
  {
    name: 'Marrakech Medina',
    description: 'Vibrant ancient walled city filled with colorful souks, mesmerizing palaces, beautiful gardens, and aromatic Moroccan cuisine.',
    category: 'Shopping',
    latitude: 31.6295,
    longitude: -7.9811,
    address: 'Medina, Marrakech, Morocco',
    city: 'Marrakech',
    country: 'Morocco',
    priceRange: 'Budget',
    rating: 4.6,
    reviews: 7200,
    openingHours: '9:00 AM - 9:00 PM',
    image: 'https://images.unsplash.com/photo-1539020140153-e479b8c22e70?w=400&h=300&fit=crop'
  }
]

const connectAndSeed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI)
    console.log('✓ Connected to MongoDB')

    // Clear existing places
    await Place.deleteMany({})
    console.log('✓ Cleared existing places')

    // Insert seed data
    const result = await Place.insertMany(seedPlaces)
    console.log(`✓ Inserted ${result.length} places`)

    await mongoose.connection.close()
    console.log('✓ Database connection closed')
  } catch (error) {
    console.error('✗ Seeding error:', error.message)
    process.exit(1)
  }
}

connectAndSeed()
